import jsPDF from "jspdf";
import type { ToolboxTalkDocument } from "@/lib/types";

const PAGE_MARGIN = 20;
const PAGE_WIDTH = 210;
const CONTENT_WIDTH = PAGE_WIDTH - PAGE_MARGIN * 2;
const LINE_HEIGHT = 6;
const SECTION_GAP = 8;
const BLUE = [30, 64, 175] as const;
const DARK = [23, 23, 23] as const;
const GRAY = [100, 100, 100] as const;
const AMBER = [217, 119, 6] as const;

function addNewPageIfNeeded(
  doc: jsPDF,
  y: number,
  needed: number
): number {
  if (y + needed > 275) {
    doc.addPage();
    return PAGE_MARGIN;
  }
  return y;
}

function wrapText(
  doc: jsPDF,
  text: string,
  maxWidth: number
): string[] {
  return doc.splitTextToSize(text, maxWidth) as string[];
}

export function generateToolboxTalkPdf(
  document: ToolboxTalkDocument
): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm" });
  let y = PAGE_MARGIN;

  // Header bar
  doc.setFillColor(...BLUE);
  doc.rect(0, 0, PAGE_WIDTH, 35, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("SafetyDocs Pro", PAGE_MARGIN, 14);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("OSHA Toolbox Talk", PAGE_MARGIN, 22);
  doc.text(document.date, PAGE_WIDTH - PAGE_MARGIN, 14, {
    align: "right",
  });
  doc.text(document.companyName, PAGE_WIDTH - PAGE_MARGIN, 22, {
    align: "right",
  });
  y = 42;

  // Title
  doc.setTextColor(...DARK);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  const titleLines = wrapText(doc, document.title, CONTENT_WIDTH);
  for (const line of titleLines) {
    y = addNewPageIfNeeded(doc, y, LINE_HEIGHT + 2);
    doc.text(line, PAGE_MARGIN, y);
    y += 8;
  }
  y += 2;

  // Meta info
  doc.setFontSize(10);
  doc.setTextColor(...GRAY);
  doc.setFont("helvetica", "normal");
  doc.text(`Trade: ${document.trade}`, PAGE_MARGIN, y);
  y += 5;
  doc.text(
    `Location: ${document.projectLocation}`,
    PAGE_MARGIN,
    y
  );
  y += SECTION_GAP;

  // Divider
  doc.setDrawColor(...AMBER);
  doc.setLineWidth(0.5);
  doc.line(PAGE_MARGIN, y, PAGE_WIDTH - PAGE_MARGIN, y);
  y += SECTION_GAP;

  // Sections
  for (const section of document.sections) {
    y = addNewPageIfNeeded(doc, y, 20);

    // Section heading
    doc.setTextColor(...BLUE);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(section.heading.toUpperCase(), PAGE_MARGIN, y);
    y += LINE_HEIGHT + 2;

    // Section content
    doc.setTextColor(...DARK);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    const paragraphs = section.content.split("\n");
    for (const paragraph of paragraphs) {
      if (!paragraph.trim()) {
        y += 3;
        continue;
      }
      const lines = wrapText(doc, paragraph.trim(), CONTENT_WIDTH);
      for (const line of lines) {
        y = addNewPageIfNeeded(doc, y, LINE_HEIGHT);
        doc.text(line, PAGE_MARGIN, y);
        y += LINE_HEIGHT;
      }
      y += 2;
    }

    y += SECTION_GAP;
  }

  // OSHA References
  if (document.oshaReferences.length > 0) {
    y = addNewPageIfNeeded(doc, y, 20);
    doc.setDrawColor(...AMBER);
    doc.line(PAGE_MARGIN, y, PAGE_WIDTH - PAGE_MARGIN, y);
    y += SECTION_GAP;

    doc.setTextColor(...BLUE);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("OSHA REGULATION REFERENCES", PAGE_MARGIN, y);
    y += LINE_HEIGHT + 2;

    doc.setTextColor(...DARK);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    for (const ref of document.oshaReferences) {
      y = addNewPageIfNeeded(doc, y, LINE_HEIGHT);
      doc.text(`  ${ref}`, PAGE_MARGIN, y);
      y += LINE_HEIGHT;
    }
  }

  // Signature block
  y = addNewPageIfNeeded(doc, y, 40);
  y += 10;
  doc.setDrawColor(...GRAY);
  doc.setLineWidth(0.3);
  doc.line(PAGE_MARGIN, y, PAGE_MARGIN + 70, y);
  doc.line(PAGE_MARGIN + 90, y, PAGE_WIDTH - PAGE_MARGIN, y);
  y += 5;
  doc.setTextColor(...GRAY);
  doc.setFontSize(9);
  doc.text("Presenter Signature", PAGE_MARGIN, y);
  doc.text("Date", PAGE_MARGIN + 90, y);
  y += 10;
  doc.text(
    "Attendees: ________________________________________",
    PAGE_MARGIN,
    y
  );
  y += LINE_HEIGHT;
  doc.text(
    "________________________________________________________",
    PAGE_MARGIN,
    y
  );

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...GRAY);
    doc.text(
      `Generated by SafetyDocs Pro | Page ${i} of ${pageCount}`,
      PAGE_WIDTH / 2,
      290,
      { align: "center" }
    );
  }

  return doc;
}
